### ISSUE TITLE
Missing .env and error in geo-stream-kafka_producer docker

### ISSUE THREAD

**Issue by mtvu** [iwpnd/geo-stream-kafka#4]
Thanks for putting together this example. I encountered an issue when building the app . The env_file is not available in the geostream folder which caused the docker compose to fail. So I removed it. 

 env_file:
      - ./geostream/.env

When checking  geo-stream-kafka_producer docker I saw the following error . Hope you can help .

```  
File "./app/main.py", line 5, in <module>
    from app.core.config import KAFKA_INSTANCE
  File "./app/core/config.py", line 12, in <module>
    KAFKA_URI: str = config("KAFKA_URI")
  File "/usr/local/lib/python3.7/site-packages/starlette/config.py", line 62, in __call__
    return self.get(key, cast, default)
  File "/usr/local/lib/python3.7/site-packages/starlette/config.py", line 75, in get
    raise KeyError(f"Config '{key}' is missing, and has no default.")
KeyError: "Config 'KAFKA_URI' is missing, and has no default."
```

**Comment by iwpnd** [comment]
hi @mtvu, sorry for the late reply. I guess I should've added the information in the readme. The consumer, as well as the producer have a [config.py](https://github.com/iwpnd/geo-stream-kafka/blob/master/geostream/producer/app/core/config.py) that is looking for an .env file and in there for the `KAFKA_URL` and `KAFKA_PORT`. You can either provide an `.env` file or you set the parameter yourself.
