### ISSUE TITLE
Missing .env

### ISSUE THREAD

**Issue by vjanz** [iwpnd/geo-stream-kafka#5]
Great job on the article and the project here 🚀 

I see that here is missing .env_example or .env specifically. I think it supposed to be on /geostream directory.

Best,

**Comment by iwpnd** [comment]
Both consumer and producer have config.py that tells you the environment variables necessary. https://github.com/iwpnd/geo-stream-kafka/blob/master/geostream/consumer/app/core/config.py https://github.com/iwpnd/geo-stream-kafka/blob/master/geostream/producer/app/core/config.py

**Comment by vjanz** [comment]
Hi @iwpnd ,

Yes, I understand that there is config.py that shows basically which environment variables the user should provide, but since you decided to keep this open source it would be good if you could tell how you pass these environment variables by pushing them to the repository .env_example file, which others can use.

Thanks,

Best,

**Comment by iwpnd** [comment]
@vjanz keeping it open source does not obligate me to maintain or improve it. feel free to submit a PR and I will merge it, but im not spending any more time on it other than security updates.
